---
asset_path: "../../dist/"
mailchimp_key: "4df049b873c7e2d5d08416ecfac6eee4-us9"
bitcoin:
  HttpPostMode: true
  DisableTLS: true
  Host: localhost:18332
  User: bitcoinrpc
  Pass: D7YKqDXM5nuhHhAn6xkiMYaapiDfBKzHwCUfLFbVNZkK

