---
server:
  Https_Port: ":8443"
  Http_Port: ":8080"
  Asset_Path: "../../dist/"
  SSL_Host: "ssl.bursa.io"
  Allowed_Hosts:
    - "bursa.io"
    - "blog.bursa.io"
    - "ssl.bursa.io"

email:
  Mailchimp_Key: "4df049b873c7e2d5d08416ecfac6eee4-us9"

bitcoin:
  HttpPostMode: true
  DisableTLS: false,
  # TODO firewall this
  Host: '127.0.0.1:8332'
  # TODO change this
  User: 'bitcoinrpc'
  Pass: 'D7YKqDXM5nuhHhAn6xkiMYaapiDfBKzHwCUfLFbVNZkK'
sessions_key: 'GtdxzNHRNhJsLmKVywQX8wo8TRRZ'
database:
  connect_retries: 5

app:
  Logic_Url: "/login"
