---
ports:
  http: ":8080"
  https: ":8443"
paths: 
  assets: "./assets"
  templates: "./assets/views"
  partials: "./assets/views/partials"
  statics: "./static"

ssl: 
  host: "ssl.bursa.io"
  allowed_hosts:
    - "bursa.io"
    - "blog.bursa.io"
    - "ssl.bursa.io"

email:
  Mailchimp_Key: "4df049b873c7e2d5d08416ecfac6eee4-us9"

bitcoin:
  HttpPostMode: true
  DisableTLS: true
  Host: localhost:18332
  User: bitcoinrpc
  Pass: D7YKqDXM5nuhHhAn6xkiMYaapiDfBKzHwCUfLFbVNZkK

app:
  Login_Url: "/login"
