---
driver:
  name: vagrant
  network:
    - ["private_network", { ip: "10.1.3.7" }]
    - ["forwarded_port", {guest: 80, host: 8080}]
  synced_folders:
    - ["../../", "/bursa", "create: true"]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - role[all]
      - recipe[bursa::default]
    attributes:
